### ISSUE TITLE
Do you want to keep the project?

### ISSUE THREAD

**Issue by jhonathas** [san650/phoenix_components#35]
I started making a dependency for components in Phoenix and found yours that if it was up to date would work for me. Do you intend to continue it?

**Comment by san650** [comment]
Hi @jhonathas,

I'm using this package in a couple of projects and my intention is to continue improving it. I have some plans for a next version that fixes some annoyances that I've found while using it for some time.

I would love to hear feedback about the library or ideas in general 😃

**Comment by jhonathas** [comment]
How cool, it will be very useful to me. Do you accept pull requests in case I add some improvement?

**Comment by san650** [comment]
@jhonathas 

> Do you accept pull requests in case I add some improvement?

Always!!

And if you want to help me maintaining this library, that would be wonderful!

**Comment by viniciussbs** [comment]
@san650 I work with @jhonathas and I'm willing to contribute to this project. Just to let you know. :)

**Comment by san650** [comment]
@viniciussbs that's awesome! I'm really happy that you found the project useful, let's improve it together!
